language: python
os: linux

# Because Beryl is going to run on Python 3.6 or later
python:
  - "3.6"
  - "3.7"
#  - "3.8"
cache: pip

install:
  - pip install pipenv
  - pipenv lock -r -d > dev-requirements.txt
  - pipenv lock -r > requirements.txt
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt

script:
  - pytest
